# Generated by Django 4.2 on 2023-04-10 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HotelsApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hotels",
            old_name="Price",
            new_name="price",
        ),
    ]
