# Generated by Django 4.2 on 2023-04-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HotelsApp", "0002_rename_price_hotels_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotels",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
